#!/usr/bin/env bash

# Make vim the default editor.
export EDITOR='nano';

# Enable persistent REPL history for `node`.
export NODE_REPL_HISTORY=~/.node_history;
# Allow 32³ entries; the default is 1000.
export NODE_REPL_HISTORY_SIZE='32768';
# Use sloppy mode by default, matching web browsers.
export NODE_REPL_MODE='sloppy';

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8';


# History on steroids
#  http://unix.stackexchange.com/a/48113
export HISTCONTROL="erasedups:ignoreboth" #ignoreboth will ignore consecutive dups and commands starting with space
# Use standard ISO 8601 timestamp
# %F equivalent to %Y-%m-%d
# %T equivalent to %H:%M:%S (24-hours format)
export HISTTIMEFORMAT="%F %T "
export HISTIGNORE="hist*:ls:pwd:gl:bash:cd:la:exit:clear:z:ll:* --help"
# Increase Bash history size. Allow 32³ entries; the default is 500.
export HISTSIZE="1000000"
export HISTFILESIZE="1000000"

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';

# highlighting inside manpages and elsewhere
export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[0m'           # end mode
export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'           # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history.
# a-append c-clear r-read into memory
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"